//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPE3_Daltons.API_Daltons {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Compte_rendu", Namespace="http://schemas.datacontract.org/2004/07/API_Daltons")]
    [System.SerializableAttribute()]
    public partial class Compte_rendu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PPE3_Daltons.API_Daltons.Intervention[] InterventionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PPE3_Daltons.API_Daltons.Societe SocieteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PPE3_Daltons.API_Daltons.Societe Societe1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PPE3_Daltons.API_Daltons.Societe Societe2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PPE3_Daltons.API_Daltons.Technicien TechnicienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_compte_renduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> id_societeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_technicienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string noteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PPE3_Daltons.API_Daltons.Intervention[] Intervention {
            get {
                return this.InterventionField;
            }
            set {
                if ((object.ReferenceEquals(this.InterventionField, value) != true)) {
                    this.InterventionField = value;
                    this.RaisePropertyChanged("Intervention");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PPE3_Daltons.API_Daltons.Societe Societe {
            get {
                return this.SocieteField;
            }
            set {
                if ((object.ReferenceEquals(this.SocieteField, value) != true)) {
                    this.SocieteField = value;
                    this.RaisePropertyChanged("Societe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PPE3_Daltons.API_Daltons.Societe Societe1 {
            get {
                return this.Societe1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Societe1Field, value) != true)) {
                    this.Societe1Field = value;
                    this.RaisePropertyChanged("Societe1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PPE3_Daltons.API_Daltons.Societe Societe2 {
            get {
                return this.Societe2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Societe2Field, value) != true)) {
                    this.Societe2Field = value;
                    this.RaisePropertyChanged("Societe2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PPE3_Daltons.API_Daltons.Technicien Technicien {
            get {
                return this.TechnicienField;
            }
            set {
                if ((object.ReferenceEquals(this.TechnicienField, value) != true)) {
                    this.TechnicienField = value;
                    this.RaisePropertyChanged("Technicien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_compte_rendu {
            get {
                return this.id_compte_renduField;
            }
            set {
                if ((this.id_compte_renduField.Equals(value) != true)) {
                    this.id_compte_renduField = value;
                    this.RaisePropertyChanged("id_compte_rendu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_societe {
            get {
                return this.id_societeField;
            }
            set {
                if ((this.id_societeField.Equals(value) != true)) {
                    this.id_societeField = value;
                    this.RaisePropertyChanged("id_societe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_technicien {
            get {
                return this.id_technicienField;
            }
            set {
                if ((this.id_technicienField.Equals(value) != true)) {
                    this.id_technicienField = value;
                    this.RaisePropertyChanged("id_technicien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string note {
            get {
                return this.noteField;
            }
            set {
                if ((object.ReferenceEquals(this.noteField, value) != true)) {
                    this.noteField = value;
                    this.RaisePropertyChanged("note");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Societe", Namespace="http://schemas.datacontract.org/2004/07/API_Daltons")]
    [System.SerializableAttribute()]
    public partial class Societe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PPE3_Daltons.API_Daltons.Compte_rendu[] Compte_renduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PPE3_Daltons.API_Daltons.Compte_rendu[] Compte_rendu1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PPE3_Daltons.API_Daltons.Compte_rendu[] Compte_rendu2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PPE3_Daltons.API_Daltons.Intervention[] InterventionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string adresse_societeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cp_societeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string email_societeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_societeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_societeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tel_societeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ville_societeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PPE3_Daltons.API_Daltons.Compte_rendu[] Compte_rendu {
            get {
                return this.Compte_renduField;
            }
            set {
                if ((object.ReferenceEquals(this.Compte_renduField, value) != true)) {
                    this.Compte_renduField = value;
                    this.RaisePropertyChanged("Compte_rendu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PPE3_Daltons.API_Daltons.Compte_rendu[] Compte_rendu1 {
            get {
                return this.Compte_rendu1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Compte_rendu1Field, value) != true)) {
                    this.Compte_rendu1Field = value;
                    this.RaisePropertyChanged("Compte_rendu1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PPE3_Daltons.API_Daltons.Compte_rendu[] Compte_rendu2 {
            get {
                return this.Compte_rendu2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Compte_rendu2Field, value) != true)) {
                    this.Compte_rendu2Field = value;
                    this.RaisePropertyChanged("Compte_rendu2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PPE3_Daltons.API_Daltons.Intervention[] Intervention {
            get {
                return this.InterventionField;
            }
            set {
                if ((object.ReferenceEquals(this.InterventionField, value) != true)) {
                    this.InterventionField = value;
                    this.RaisePropertyChanged("Intervention");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string adresse_societe {
            get {
                return this.adresse_societeField;
            }
            set {
                if ((object.ReferenceEquals(this.adresse_societeField, value) != true)) {
                    this.adresse_societeField = value;
                    this.RaisePropertyChanged("adresse_societe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cp_societe {
            get {
                return this.cp_societeField;
            }
            set {
                if ((object.ReferenceEquals(this.cp_societeField, value) != true)) {
                    this.cp_societeField = value;
                    this.RaisePropertyChanged("cp_societe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email_societe {
            get {
                return this.email_societeField;
            }
            set {
                if ((object.ReferenceEquals(this.email_societeField, value) != true)) {
                    this.email_societeField = value;
                    this.RaisePropertyChanged("email_societe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_societe {
            get {
                return this.id_societeField;
            }
            set {
                if ((this.id_societeField.Equals(value) != true)) {
                    this.id_societeField = value;
                    this.RaisePropertyChanged("id_societe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_societe {
            get {
                return this.nom_societeField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_societeField, value) != true)) {
                    this.nom_societeField = value;
                    this.RaisePropertyChanged("nom_societe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tel_societe {
            get {
                return this.tel_societeField;
            }
            set {
                if ((object.ReferenceEquals(this.tel_societeField, value) != true)) {
                    this.tel_societeField = value;
                    this.RaisePropertyChanged("tel_societe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ville_societe {
            get {
                return this.ville_societeField;
            }
            set {
                if ((object.ReferenceEquals(this.ville_societeField, value) != true)) {
                    this.ville_societeField = value;
                    this.RaisePropertyChanged("ville_societe");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Technicien", Namespace="http://schemas.datacontract.org/2004/07/API_Daltons")]
    [System.SerializableAttribute()]
    public partial class Technicien : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PPE3_Daltons.API_Daltons.Compte_rendu[] Compte_renduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PPE3_Daltons.API_Daltons.Intervention[] InterventionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PPE3_Daltons.API_Daltons.Materiel MaterielField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_materielField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_technicienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prenomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PPE3_Daltons.API_Daltons.Compte_rendu[] Compte_rendu {
            get {
                return this.Compte_renduField;
            }
            set {
                if ((object.ReferenceEquals(this.Compte_renduField, value) != true)) {
                    this.Compte_renduField = value;
                    this.RaisePropertyChanged("Compte_rendu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PPE3_Daltons.API_Daltons.Intervention[] Intervention {
            get {
                return this.InterventionField;
            }
            set {
                if ((object.ReferenceEquals(this.InterventionField, value) != true)) {
                    this.InterventionField = value;
                    this.RaisePropertyChanged("Intervention");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PPE3_Daltons.API_Daltons.Materiel Materiel {
            get {
                return this.MaterielField;
            }
            set {
                if ((object.ReferenceEquals(this.MaterielField, value) != true)) {
                    this.MaterielField = value;
                    this.RaisePropertyChanged("Materiel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_materiel {
            get {
                return this.id_materielField;
            }
            set {
                if ((this.id_materielField.Equals(value) != true)) {
                    this.id_materielField = value;
                    this.RaisePropertyChanged("id_materiel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_technicien {
            get {
                return this.id_technicienField;
            }
            set {
                if ((this.id_technicienField.Equals(value) != true)) {
                    this.id_technicienField = value;
                    this.RaisePropertyChanged("id_technicien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                if ((object.ReferenceEquals(this.nomField, value) != true)) {
                    this.nomField = value;
                    this.RaisePropertyChanged("nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prenom {
            get {
                return this.prenomField;
            }
            set {
                if ((object.ReferenceEquals(this.prenomField, value) != true)) {
                    this.prenomField = value;
                    this.RaisePropertyChanged("prenom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tel {
            get {
                return this.telField;
            }
            set {
                if ((object.ReferenceEquals(this.telField, value) != true)) {
                    this.telField = value;
                    this.RaisePropertyChanged("tel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Intervention", Namespace="http://schemas.datacontract.org/2004/07/API_Daltons")]
    [System.SerializableAttribute()]
    public partial class Intervention : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PPE3_Daltons.API_Daltons.Compte_rendu Compte_renduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PPE3_Daltons.API_Daltons.Etat_intervention Etat_interventionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PPE3_Daltons.API_Daltons.Motif_intervention Motif_interventionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PPE3_Daltons.API_Daltons.Societe SocieteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PPE3_Daltons.API_Daltons.Technicien TechnicienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime date_interventionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> id_compte_renduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_etatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_interventionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_motifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_societeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_technicienField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PPE3_Daltons.API_Daltons.Compte_rendu Compte_rendu {
            get {
                return this.Compte_renduField;
            }
            set {
                if ((object.ReferenceEquals(this.Compte_renduField, value) != true)) {
                    this.Compte_renduField = value;
                    this.RaisePropertyChanged("Compte_rendu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PPE3_Daltons.API_Daltons.Etat_intervention Etat_intervention {
            get {
                return this.Etat_interventionField;
            }
            set {
                if ((object.ReferenceEquals(this.Etat_interventionField, value) != true)) {
                    this.Etat_interventionField = value;
                    this.RaisePropertyChanged("Etat_intervention");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PPE3_Daltons.API_Daltons.Motif_intervention Motif_intervention {
            get {
                return this.Motif_interventionField;
            }
            set {
                if ((object.ReferenceEquals(this.Motif_interventionField, value) != true)) {
                    this.Motif_interventionField = value;
                    this.RaisePropertyChanged("Motif_intervention");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PPE3_Daltons.API_Daltons.Societe Societe {
            get {
                return this.SocieteField;
            }
            set {
                if ((object.ReferenceEquals(this.SocieteField, value) != true)) {
                    this.SocieteField = value;
                    this.RaisePropertyChanged("Societe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PPE3_Daltons.API_Daltons.Technicien Technicien {
            get {
                return this.TechnicienField;
            }
            set {
                if ((object.ReferenceEquals(this.TechnicienField, value) != true)) {
                    this.TechnicienField = value;
                    this.RaisePropertyChanged("Technicien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date_intervention {
            get {
                return this.date_interventionField;
            }
            set {
                if ((this.date_interventionField.Equals(value) != true)) {
                    this.date_interventionField = value;
                    this.RaisePropertyChanged("date_intervention");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_compte_rendu {
            get {
                return this.id_compte_renduField;
            }
            set {
                if ((this.id_compte_renduField.Equals(value) != true)) {
                    this.id_compte_renduField = value;
                    this.RaisePropertyChanged("id_compte_rendu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_etat {
            get {
                return this.id_etatField;
            }
            set {
                if ((this.id_etatField.Equals(value) != true)) {
                    this.id_etatField = value;
                    this.RaisePropertyChanged("id_etat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_intervention {
            get {
                return this.id_interventionField;
            }
            set {
                if ((this.id_interventionField.Equals(value) != true)) {
                    this.id_interventionField = value;
                    this.RaisePropertyChanged("id_intervention");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_motif {
            get {
                return this.id_motifField;
            }
            set {
                if ((this.id_motifField.Equals(value) != true)) {
                    this.id_motifField = value;
                    this.RaisePropertyChanged("id_motif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_societe {
            get {
                return this.id_societeField;
            }
            set {
                if ((this.id_societeField.Equals(value) != true)) {
                    this.id_societeField = value;
                    this.RaisePropertyChanged("id_societe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_technicien {
            get {
                return this.id_technicienField;
            }
            set {
                if ((this.id_technicienField.Equals(value) != true)) {
                    this.id_technicienField = value;
                    this.RaisePropertyChanged("id_technicien");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Etat_intervention", Namespace="http://schemas.datacontract.org/2004/07/API_Daltons")]
    [System.SerializableAttribute()]
    public partial class Etat_intervention : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PPE3_Daltons.API_Daltons.Etat_intervention Etat_intervention1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PPE3_Daltons.API_Daltons.Etat_intervention Etat_intervention2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PPE3_Daltons.API_Daltons.Intervention[] InterventionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_etatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string libelleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PPE3_Daltons.API_Daltons.Etat_intervention Etat_intervention1 {
            get {
                return this.Etat_intervention1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Etat_intervention1Field, value) != true)) {
                    this.Etat_intervention1Field = value;
                    this.RaisePropertyChanged("Etat_intervention1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PPE3_Daltons.API_Daltons.Etat_intervention Etat_intervention2 {
            get {
                return this.Etat_intervention2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Etat_intervention2Field, value) != true)) {
                    this.Etat_intervention2Field = value;
                    this.RaisePropertyChanged("Etat_intervention2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PPE3_Daltons.API_Daltons.Intervention[] Intervention {
            get {
                return this.InterventionField;
            }
            set {
                if ((object.ReferenceEquals(this.InterventionField, value) != true)) {
                    this.InterventionField = value;
                    this.RaisePropertyChanged("Intervention");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_etat {
            get {
                return this.id_etatField;
            }
            set {
                if ((this.id_etatField.Equals(value) != true)) {
                    this.id_etatField = value;
                    this.RaisePropertyChanged("id_etat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string libelle {
            get {
                return this.libelleField;
            }
            set {
                if ((object.ReferenceEquals(this.libelleField, value) != true)) {
                    this.libelleField = value;
                    this.RaisePropertyChanged("libelle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Motif_intervention", Namespace="http://schemas.datacontract.org/2004/07/API_Daltons")]
    [System.SerializableAttribute()]
    public partial class Motif_intervention : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PPE3_Daltons.API_Daltons.Intervention[] InterventionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_motifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string libelleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double prix_hField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PPE3_Daltons.API_Daltons.Intervention[] Intervention {
            get {
                return this.InterventionField;
            }
            set {
                if ((object.ReferenceEquals(this.InterventionField, value) != true)) {
                    this.InterventionField = value;
                    this.RaisePropertyChanged("Intervention");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_motif {
            get {
                return this.id_motifField;
            }
            set {
                if ((this.id_motifField.Equals(value) != true)) {
                    this.id_motifField = value;
                    this.RaisePropertyChanged("id_motif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string libelle {
            get {
                return this.libelleField;
            }
            set {
                if ((object.ReferenceEquals(this.libelleField, value) != true)) {
                    this.libelleField = value;
                    this.RaisePropertyChanged("libelle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double prix_h {
            get {
                return this.prix_hField;
            }
            set {
                if ((this.prix_hField.Equals(value) != true)) {
                    this.prix_hField = value;
                    this.RaisePropertyChanged("prix_h");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Materiel", Namespace="http://schemas.datacontract.org/2004/07/API_Daltons")]
    [System.SerializableAttribute()]
    public partial class Materiel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PPE3_Daltons.API_Daltons.Technicien[] TechnicienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_materielField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modeleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string num_serieField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PPE3_Daltons.API_Daltons.Technicien[] Technicien {
            get {
                return this.TechnicienField;
            }
            set {
                if ((object.ReferenceEquals(this.TechnicienField, value) != true)) {
                    this.TechnicienField = value;
                    this.RaisePropertyChanged("Technicien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_materiel {
            get {
                return this.id_materielField;
            }
            set {
                if ((this.id_materielField.Equals(value) != true)) {
                    this.id_materielField = value;
                    this.RaisePropertyChanged("id_materiel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ip {
            get {
                return this.ipField;
            }
            set {
                if ((object.ReferenceEquals(this.ipField, value) != true)) {
                    this.ipField = value;
                    this.RaisePropertyChanged("ip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string modele {
            get {
                return this.modeleField;
            }
            set {
                if ((object.ReferenceEquals(this.modeleField, value) != true)) {
                    this.modeleField = value;
                    this.RaisePropertyChanged("modele");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string num_serie {
            get {
                return this.num_serieField;
            }
            set {
                if ((object.ReferenceEquals(this.num_serieField, value) != true)) {
                    this.num_serieField = value;
                    this.RaisePropertyChanged("num_serie");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="API_Daltons.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCompte_Rendu", ReplyAction="http://tempuri.org/IService1/AddCompte_RenduResponse")]
        int AddCompte_Rendu(PPE3_Daltons.API_Daltons.Compte_rendu compte_rendu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddIntervention", ReplyAction="http://tempuri.org/IService1/AddInterventionResponse")]
        int AddIntervention(PPE3_Daltons.API_Daltons.Intervention intervention);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddSociete", ReplyAction="http://tempuri.org/IService1/AddSocieteResponse")]
        int AddSociete(PPE3_Daltons.API_Daltons.Societe societe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddTechnicien", ReplyAction="http://tempuri.org/IService1/AddTechnicienResponse")]
        int AddTechnicien(PPE3_Daltons.API_Daltons.Technicien technicien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCompte_Rendu", ReplyAction="http://tempuri.org/IService1/DeleteCompte_RenduResponse")]
        void DeleteCompte_Rendu(PPE3_Daltons.API_Daltons.Compte_rendu compte_rendu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteIntervention", ReplyAction="http://tempuri.org/IService1/DeleteInterventionResponse")]
        void DeleteIntervention(PPE3_Daltons.API_Daltons.Intervention intervention);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteMateriel", ReplyAction="http://tempuri.org/IService1/DeleteMaterielResponse")]
        void DeleteMateriel(PPE3_Daltons.API_Daltons.Materiel materiel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteSociete", ReplyAction="http://tempuri.org/IService1/DeleteSocieteResponse")]
        void DeleteSociete(PPE3_Daltons.API_Daltons.Societe societe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteTechnicien", ReplyAction="http://tempuri.org/IService1/DeleteTechnicienResponse")]
        void DeleteTechnicien(PPE3_Daltons.API_Daltons.Technicien technicien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchCompte_rendu", ReplyAction="http://tempuri.org/IService1/SearchCompte_renduResponse")]
        PPE3_Daltons.API_Daltons.Compte_rendu[] SearchCompte_rendu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchIntervention", ReplyAction="http://tempuri.org/IService1/SearchInterventionResponse")]
        PPE3_Daltons.API_Daltons.Intervention[] SearchIntervention();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchMateriel", ReplyAction="http://tempuri.org/IService1/SearchMaterielResponse")]
        PPE3_Daltons.API_Daltons.Materiel[] SearchMateriel();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchSociete", ReplyAction="http://tempuri.org/IService1/SearchSocieteResponse")]
        PPE3_Daltons.API_Daltons.Societe[] SearchSociete();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchTechnicien", ReplyAction="http://tempuri.org/IService1/SearchTechnicienResponse")]
        PPE3_Daltons.API_Daltons.Technicien[] SearchTechnicien();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchMotif", ReplyAction="http://tempuri.org/IService1/SearchMotifResponse")]
        PPE3_Daltons.API_Daltons.Motif_intervention[] SearchMotif();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UPDSociete", ReplyAction="http://tempuri.org/IService1/UPDSocieteResponse")]
        void UPDSociete(PPE3_Daltons.API_Daltons.Societe societe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UPDCompte_rendu", ReplyAction="http://tempuri.org/IService1/UPDCompte_renduResponse")]
        void UPDCompte_rendu(PPE3_Daltons.API_Daltons.Compte_rendu compte_rendu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UPDTechnicien", ReplyAction="http://tempuri.org/IService1/UPDTechnicienResponse")]
        void UPDTechnicien(PPE3_Daltons.API_Daltons.Technicien technicien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UPDIntervention", ReplyAction="http://tempuri.org/IService1/UPDInterventionResponse")]
        void UPDIntervention(PPE3_Daltons.API_Daltons.Intervention intervention);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PPE3_Daltons.API_Daltons.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PPE3_Daltons.API_Daltons.IService1>, PPE3_Daltons.API_Daltons.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddCompte_Rendu(PPE3_Daltons.API_Daltons.Compte_rendu compte_rendu) {
            return base.Channel.AddCompte_Rendu(compte_rendu);
        }
        
        public int AddIntervention(PPE3_Daltons.API_Daltons.Intervention intervention) {
            return base.Channel.AddIntervention(intervention);
        }
        
        public int AddSociete(PPE3_Daltons.API_Daltons.Societe societe) {
            return base.Channel.AddSociete(societe);
        }
        
        public int AddTechnicien(PPE3_Daltons.API_Daltons.Technicien technicien) {
            return base.Channel.AddTechnicien(technicien);
        }
        
        public void DeleteCompte_Rendu(PPE3_Daltons.API_Daltons.Compte_rendu compte_rendu) {
            base.Channel.DeleteCompte_Rendu(compte_rendu);
        }
        
        public void DeleteIntervention(PPE3_Daltons.API_Daltons.Intervention intervention) {
            base.Channel.DeleteIntervention(intervention);
        }
        
        public void DeleteMateriel(PPE3_Daltons.API_Daltons.Materiel materiel) {
            base.Channel.DeleteMateriel(materiel);
        }
        
        public void DeleteSociete(PPE3_Daltons.API_Daltons.Societe societe) {
            base.Channel.DeleteSociete(societe);
        }
        
        public void DeleteTechnicien(PPE3_Daltons.API_Daltons.Technicien technicien) {
            base.Channel.DeleteTechnicien(technicien);
        }
        
        public PPE3_Daltons.API_Daltons.Compte_rendu[] SearchCompte_rendu() {
            return base.Channel.SearchCompte_rendu();
        }
        
        public PPE3_Daltons.API_Daltons.Intervention[] SearchIntervention() {
            return base.Channel.SearchIntervention();
        }
        
        public PPE3_Daltons.API_Daltons.Materiel[] SearchMateriel() {
            return base.Channel.SearchMateriel();
        }
        
        public PPE3_Daltons.API_Daltons.Societe[] SearchSociete() {
            return base.Channel.SearchSociete();
        }
        
        public PPE3_Daltons.API_Daltons.Technicien[] SearchTechnicien() {
            return base.Channel.SearchTechnicien();
        }
        
        public PPE3_Daltons.API_Daltons.Motif_intervention[] SearchMotif() {
            return base.Channel.SearchMotif();
        }
        
        public void UPDSociete(PPE3_Daltons.API_Daltons.Societe societe) {
            base.Channel.UPDSociete(societe);
        }
        
        public void UPDCompte_rendu(PPE3_Daltons.API_Daltons.Compte_rendu compte_rendu) {
            base.Channel.UPDCompte_rendu(compte_rendu);
        }
        
        public void UPDTechnicien(PPE3_Daltons.API_Daltons.Technicien technicien) {
            base.Channel.UPDTechnicien(technicien);
        }
        
        public void UPDIntervention(PPE3_Daltons.API_Daltons.Intervention intervention) {
            base.Channel.UPDIntervention(intervention);
        }
    }
}
